### ISSUE TITLE
docs seem incorrect about config options

### ISSUE THREAD

**Issue by phinds1** [evis/scalafix-maven-plugin#153]
added exactly 

			<plugin>
				<groupId>io.github.evis</groupId>
				<artifactId>scalafix-maven-plugin_2.13</artifactId>
				<version>0.1.8_0.11.0</version>
				<configuration>
					<sourceDirectory>src/main/helm/gatling</sourceDirectory>
				</configuration>
			</plugin>
			
per docs and I get 			

[WARNING] Parameter 'sourceDirectory' is unknown for plugin 'scalafix-maven-plugin_2.13:0.1.8_0.11.0:scalafix (default-cli)'

**Comment by evis** [comment]
Thank you, the docs was wrong. Fixed it, check the updated readme.
