### ISSUE TITLE
No 0.1.9 release for Scala 2.12

### ISSUE THREAD

**Issue by UnaiUribarri-TomTom** [evis/scalafix-maven-plugin#177]
After carefully following the instructions in the README, I get this error:

```
Could not find artifact io.github.evis:scalafix-maven-plugin_2.12:pom:0.1.9_0.12.1 in maven-central
```

Checking [here](https://mvnrepository.com/artifact/io.github.evis/scalafix-maven-plugin), I see that it was only released for Scala 2.13.

It seems that you forgot to build this last version for Scala 2.12 or silently deprecated Scala 2.12.

**Comment by UnaiUribarri-TomTom** [comment]
Same results here: https://central.sonatype.com/search?q=scalafix-maven-plugin

**Comment by evis** [comment]
I'm sorry about that, I've forgot to build it. Now I encounter some strange error during deploying artifact for Scala 2.12, going to deal with it in several days

**Comment by evis** [comment]
I have deployed the artifact version 0.1.9_0.12.1 for Scala 2.12. It should appear in Maven Central within a few hours. Thank you for reporting the issue!
