### ISSUE TITLE
Release for Scalafix 0.9.32 (Scala 2.13.7 compatible)?

### ISSUE THREAD

**Issue by andreisilviudragnea** [evis/scalafix-maven-plugin#20]
When is the Maven plugin gonna be released for [Scalafix v0.9.32](https://github.com/scalacenter/scalafix/releases/tag/v0.9.32) (also compatible with Scala 2.13.7)?

**Comment by andreisilviudragnea** [comment]
@evis Is this project maintained anymore?

**Comment by evis** [comment]
I'm sorry for the delay, I will take a look this week.

**Comment by evis** [comment]
Resolved by #20.
