### ISSUE TITLE
My files are not being modified

### ISSUE THREAD

**Issue by rusucosmin** [evis/scalafix-maven-plugin#4]
Hi, I'm using RemoveUnused feature and it seems like it spits out a lot of Warnings, but shouldn't it remove the imports as well? And when I git diff I should see the code changes?

**Comment by evis** [comment]
Hi @rusucosmin, I'm so sorry for the long delay :(

Yes, with default configuration it definitely should remove imports. Could you please show your `pom.xml`, at least part related to plugin configuration? Maybe, there is `scalafix.mode` option passed with value `CHECK`? Then it will just show warnings.

Feel free to check related docs about configuration:
https://github.com/evis/scalafix-maven-plugin#usage
https://github.com/evis/scalafix-maven-plugin#plugin-parameters

**Comment by rusucosmin** [comment]
Here it is my `pom.xml` related part:

```      <plugin>
        <groupId>io.github.evis</groupId>
        <artifactId>scalafix-maven-plugin</artifactId>
        <version>0.1.2_0.9.5</version>
        <configuration>
          <commandLineArgs>
            path/to/some/files/ClassThatITryToFix.scala
          </commandLineArgs>
          <args>
            <arg>-Ywarn-unused</arg> <!-- if you need exactly RemoveUnused -->
          </args>
          <compilerPlugins>
            <compilerPlugin>
              <groupId>org.scalameta</groupId>
              <artifactId>semanticdb-scalac_${scala.version}</artifactId>
              <version>${semanticdb.version}</version>
            </compilerPlugin>
          </compilerPlugins>
        </configuration>
        <dependencies>
          <dependency>
            <groupId>com.nequissimus</groupId>
            <artifactId>sort-imports_2.12</artifactId>
            <version>0.3.1</version>
          </dependency>
        </dependencies>
      </plugin>```

**Comment by nmeln** [comment]
Both `-Dscalafix.mode` and 
```
<configuration>
          <mode>IN_PLACE</mode>         
</configuration>
```
don't trigger RemoveUnused. So there is a bug with passing that parameter somewhere.

**Comment by evis** [comment]
@nmeln could you give me an example of a project, in which RemoveUnused isn't triggered? Or at least part of `pom.xml` where scalafix-maven-plugin is configured, and also a project tree.

By the way, note that either sources should be inside `/src/main/scala` directory, or you should set `sourceDirectory` configuration option. Rules should be inside a file called `.scalafix.conf` (note the dot).

**Comment by evis** [comment]
@rusucosmin I'm sorry for such a long delay, I missed your comment :-( 

Could you give me an example of a project, in which RemoveUnused isn't triggered, if it's still available? Or at least part of `pom.xml` where scalafix-maven-plugin is configured, and also a project tree.

**Comment by evis** [comment]
>           <commandLineArgs>
>             path/to/some/files/ClassThatITryToFix.scala
>           </commandLineArgs>

@rusucosmin I guess, the problem could lie here. Setting path using `commandLineArgs` isn't supported now, try using `sourceDirectory` instead, as it is mentioned in README:

https://github.com/evis/scalafix-maven-plugin/commit/6d39fbfc7086d6ea88248bda1d9dcaf0929ec53f#diff-04c6e90faac2675aa89e2176d2eec7d8R55-R66

**Comment by evis** [comment]
Feel free to reopen if the problem isn't fixed.
