### ISSUE TITLE
Support obtaining rules from github ?

### ISSUE THREAD

**Issue by jxnu-liguobin** [evis/scalafix-maven-plugin#83]
I'm not familiar with Maven. Or how to execute the following equivalent in maven plugin?
```
sbt "scalafixEnable; scalafixAll github:zio/zio/Zio2Upgrade?sha=series/2.x" 

```

**Comment by evis** [comment]
I'm so sorry for such a long delay =( But finally I've managed to deal with it =)

You should make `.scalafix.conf` in your project's root with such content:

```
rules = [
  "github:zio/zio/Zio2Upgrade?sha=series/2.x"
]
```

And then just run `mvn scalafix:scalafix`.

Hope that helps =)

Also, you can check readme file for plugin docs, and ask me any following questions in case of problems.

**Comment by evis** [comment]
Thanks for your question! I've added an answer to the "Tips and tricks" section of plugin's doc: https://github.com/evis/scalafix-maven-plugin/pull/89
